# Generated by Django 5.0.4 on 2024-05-01 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "ID",
                    models.CharField(
                        max_length=40, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("passport_data", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("purpose", models.CharField(max_length=1024)),
                (
                    "type",
                    models.CharField(
                        choices=[("IN", "Kirish"), ("OUT", "Chiqish")], max_length=3
                    ),
                ),
                (
                    "people",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="core.people",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QrCode",
            fields=[
                (
                    "ID",
                    models.CharField(
                        max_length=40, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("image_path", models.CharField(max_length=1024)),
                (
                    "type",
                    models.CharField(
                        choices=[("IN", "Kirish"), ("OUT", "Chiqish")], max_length=3
                    ),
                ),
                ("purpose", models.CharField(blank=True, max_length=1024, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "people",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qrcode",
                        to="core.people",
                    ),
                ),
            ],
        ),
    ]
